# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_test_core.ipynb.

# %% auto 0
__all__ = ['test_foo', 'TestNotebook']

# %% ../../nbs/00_test_core.ipynb 1
from ..core import *

# %% ../../nbs/01_core.ipynb 4
def test_foo(): pass

# %% ../../nbs/01_core.ipynb 14
import unittest

class TestNotebook(unittest.TestCase):
    
    def test_add(self):
        self.assertEqual(add(2, 2), 4)