# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-tdd',
                'doc_host': 'https://MJBishop.github.io',
                'git_url': 'https://github.com/MJBishop/nbdev-tdd',
                'lib_path': 'nbdev_tdd'},
  'syms': { 'nbdev_tdd.core': { 'nbdev_tdd.core.add': ('core.html#add', 'nbdev_tdd/core.py'),
                                'nbdev_tdd.core.foo': ('core.html#foo', 'nbdev_tdd/core.py'),
                                'nbdev_tdd.core.say_hello': ('core.html#say_hello', 'nbdev_tdd/core.py')},
            'nbdev_tdd.tests.test_core': { 'nbdev_tdd.tests.test_core.TestNotebook': ( 'core.html#testnotebook',
                                                                                       'nbdev_tdd/tests/test_core.py'),
                                           'nbdev_tdd.tests.test_core.TestNotebook.test_add': ( 'core.html#testnotebook.test_add',
                                                                                                'nbdev_tdd/tests/test_core.py'),
                                           'nbdev_tdd.tests.test_core.test_foo': ('core.html#test_foo', 'nbdev_tdd/tests/test_core.py')}}}
