# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto 0
__all__ = ['foo', 'say_hello', 'add']

# %% ../nbs/01_core.ipynb 3
def foo(): pass

# %% ../nbs/01_core.ipynb 5
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/01_core.ipynb 13
def add(a, b):
    return a + b
